baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Portfolio'
theme = "codey"

[params]
  # homeSubtitle = "Important links"
  [[params.social]]
    name = "email"
    url  = "mailto:polingj999@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/XarosElite"

  [[params.social]]
    name = "linkedin"
    url  = "https://linkedin.com/in/jacob-poling-497594196"
  [params.portrait]
    path     = "/img/CampingProfile.jpg"
    alt      = "Portrait"
    maxWidth = "200px"
 
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Welcome to my life"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Portfolio"

    [languages.en.params.logo]
      logoText = "Jacob Poling"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "aablog"
    name       = "Projects"
    url        = "/projects"
  [[menu.main]]
    identifier = "hobbies"
    name       = "Hobbies"
    url        = "/hobbies"
  [[menu.main]]
    identifier = "zabout"
    name       = "About"
    url        = "about/"
